{{- if and .Values.mcpServers.github.enabled .Values.mcpServers.github.agent.enabled }}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: {{ .Values.mcpServers.github.agent.name }}
  labels:
    {{- include "dwmkerr-starter-kit.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.mcpServers.github.agent.dashboardIcon }}
    ark.mckinsey.com/dashboard-icon: {{ .Values.mcpServers.github.agent.dashboardIcon | quote }}
    {{- end }}
spec:
  {{- if eq .Values.mcpServers.github.agent.model "default" }}
  # Uses default model configured in the system
  {{- else }}
  modelRef:
    name: {{ .Values.mcpServers.github.agent.model }}
  {{- end }}
  tools:
    - name: github-add-comment-to-pending-review
      type: custom
    - name: github-add-issue-comment
      type: custom
    - name: github-add-sub-issue
      type: custom
    - name: github-assign-copilot-to-issue
      type: custom
    - name: github-cancel-workflow-run
      type: custom
    - name: github-create-and-submit-pull-request-review
      type: custom
    - name: github-create-branch
      type: custom
    - name: github-create-gist
      type: custom
    - name: github-create-issue
      type: custom
    - name: github-create-or-update-file
      type: custom
    - name: github-create-pending-pull-request-review
      type: custom
    - name: github-create-pull-request
      type: custom
    - name: github-create-pull-request-with-copilot
      type: custom
    - name: github-create-repository
      type: custom
    - name: github-delete-file
      type: custom
    - name: github-delete-pending-pull-request-review
      type: custom
    - name: github-delete-workflow-run-logs
      type: custom
    - name: github-dismiss-notification
      type: custom
    - name: github-download-workflow-run-artifact
      type: custom
    - name: github-fork-repository
      type: custom
    - name: github-get-code-scanning-alert
      type: custom
    - name: github-get-commit
      type: custom
    - name: github-get-dependabot-alert
      type: custom
    - name: github-get-discussion
      type: custom
    - name: github-get-discussion-comments
      type: custom
    - name: github-get-file-contents
      type: custom
    - name: github-get-global-security-advisory
      type: custom
    - name: github-get-issue
      type: custom
    - name: github-get-issue-comments
      type: custom
    - name: github-get-job-logs
      type: custom
    - name: github-get-latest-release
      type: custom
    - name: github-get-me
      type: custom
    - name: github-get-notification-details
      type: custom
    - name: github-get-pull-request
      type: custom
    - name: github-get-pull-request-comments
      type: custom
    - name: github-get-pull-request-diff
      type: custom
    - name: github-get-pull-request-files
      type: custom
    - name: github-get-pull-request-reviews
      type: custom
    - name: github-get-pull-request-status
      type: custom
    - name: github-get-release-by-tag
      type: custom
    - name: github-get-secret-scanning-alert
      type: custom
    - name: github-get-tag
      type: custom
    - name: github-get-team-members
      type: custom
    - name: github-get-teams
      type: custom
    - name: github-get-workflow-run
      type: custom
    - name: github-get-workflow-run-logs
      type: custom
    - name: github-get-workflow-run-usage
      type: custom
    - name: github-list-branches
      type: custom
    - name: github-list-code-scanning-alerts
      type: custom
    - name: github-list-commits
      type: custom
    - name: github-list-dependabot-alerts
      type: custom
    - name: github-list-discussion-categories
      type: custom
    - name: github-list-discussions
      type: custom
    - name: github-list-gists
      type: custom
    - name: github-list-global-security-advisories
      type: custom
    - name: github-list-issue-types
      type: custom
    - name: github-list-issues
      type: custom
    - name: github-list-notifications
      type: custom
    - name: github-list-org-repository-security-advisories
      type: custom
    - name: github-list-pull-requests
      type: custom
    - name: github-list-releases
      type: custom
    - name: github-list-repository-security-advisories
      type: custom
    - name: github-list-secret-scanning-alerts
      type: custom
    - name: github-list-sub-issues
      type: custom
    - name: github-list-tags
      type: custom
    - name: github-list-workflow-jobs
      type: custom
    - name: github-list-workflow-run-artifacts
      type: custom
    - name: github-list-workflow-runs
      type: custom
    - name: github-list-workflows
      type: custom
    - name: github-manage-notification-subscription
      type: custom
    - name: github-manage-repository-notification-subscription
      type: custom
    - name: github-mark-all-notifications-read
      type: custom
    - name: github-merge-pull-request
      type: custom
    - name: github-push-files
      type: custom
    - name: github-remove-sub-issue
      type: custom
    - name: github-reprioritize-sub-issue
      type: custom
    - name: github-request-copilot-review
      type: custom
    - name: github-rerun-failed-jobs
      type: custom
    - name: github-rerun-workflow-run
      type: custom
    - name: github-run-workflow
      type: custom
    - name: github-search-code
      type: custom
    - name: github-search-issues
      type: custom
    - name: github-search-orgs
      type: custom
    - name: github-search-pull-requests
      type: custom
    - name: github-search-repositories
      type: custom
    - name: github-search-users
      type: custom
    - name: github-submit-pending-pull-request-review
      type: custom
    - name: github-update-gist
      type: custom
    - name: github-update-issue
      type: custom
    - name: github-update-pull-request
      type: custom
    - name: github-update-pull-request-branch
      type: custom
  prompt: |
{{ .Values.mcpServers.github.agent.description | nindent 4 }}
{{- end }}