apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pr-review-workflow
  annotations:
    workflows.argoproj.io/title: "Pull Requests Review"
    workflows.argoproj.io/description: |
      Analyzes all open pull requests in a GitHub repository using an ARK agent.

      GitHub Token: If gh-token is provided, the workflow can post review comments
      and status updates to PRs. Without a token, the workflow runs in read-only mode.
spec:
  entrypoint: main
  serviceAccountName: argo-workflow

  # Create a volume per-workflow execution. We will use this volume between
  # steps for shared file storage.
  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard

  arguments:
    parameters:
    - name: github-repo
      value: "mckinsey/agents-at-scale-ark"
      description: "GitHub repository in org/repo format"

    - name: updated-since
      value: "2000-01-01T00:00:00Z"
      description: "Only review PRs updated since this timestamp. Format: ISO8601 (e.g., 2024-01-01T00:00:00Z)."

    - name: pr-ids
      value: ""
      description: "Comma-separated PR IDs to review (e.g., 234,56,2). If empty, uses all open PRs matching filters."

    - name: gh-token
      value: ""
      description: "GitHub token for API access. If provided, enables PR commenting and status updates."

    - name: pr-review-agent
      value: "pr-review-agent"
      description: "Ark agent name for PR operations"

    - name: comment-on-pr
      value: "false"
      description: "If true, post review comments to PRs. Requires gh-token to be set."
      enum:
        - "true"
        - "false"


  templates:
  - name: main
    dag:
      tasks:
      - name: prepare-and-validate
        template: prepare-and-validate

      - name: request-approval
        template: request-approval
        depends: "prepare-and-validate"
        arguments:
          artifacts:
          - name: workflow-plan
            from: "{{tasks.prepare-and-validate.outputs.artifacts.workflow-plan}}"

      - name: review-prs
        template: review-pr
        depends: "request-approval"
        arguments:
          parameters:
          - name: pr-id
            value: "{{item}}"
        withParam: "{{tasks.prepare-and-validate.outputs.parameters.pr-ids}}"

      - name: comment-on-prs
        template: comment-on-pr
        depends: "review-prs"
        when: "{{workflow.parameters.comment-on-pr}} == true"
        arguments:
          parameters:
          - name: pr-id
            value: "{{item}}"
        withParam: "{{tasks.prepare-and-validate.outputs.parameters.pr-ids}}"

      - name: summarize-reviews
        template: summarize-reviews
        depends: "(comment-on-prs.Succeeded || comment-on-prs.Skipped || comment-on-prs.Failed) || (review-prs.Succeeded || review-prs.Failed)"

  - name: prepare-and-validate
    metadata:
      annotations:
        workflows.argoproj.io/description: "Validate prerequisites and fetch PRs"
    script:
      image: alpine/k8s:1.28.13
      command: [sh]
      env:
      - name: GH_TOKEN
        value: "{{workflow.parameters.gh-token}}"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail
        apk add --no-cache jq curl >/dev/null 2>&1

        # Validate prerequisites
        kubectl get mcpserver github
        kubectl wait --for=condition=Ready mcpserver/github --timeout=5s
        agent_name="{{workflow.parameters.pr-review-agent}}"
        kubectl get agent "${agent_name}"

        # Check that gh-token is provided if PR commenting is enabled
        comment_on_pr="{{workflow.parameters.comment-on-pr}}"
        gh_token="{{workflow.parameters.gh-token}}"
        if [ "${comment_on_pr}" = "true" ] && [ -z "${gh_token}" ]; then
          echo "Error: comment-on-pr is enabled but gh-token is not set" >&2
          exit 1
        fi

        # Fetch PRs
        repo="{{workflow.parameters.github-repo}}"
        pr_ids_param="{{workflow.parameters.pr-ids}}"
        updated_since="{{workflow.parameters.updated-since}}"
        workflow_id="{{workflow.name}}"
        workspace_path="/workspace/${workflow_id}"
        mkdir -p "${workspace_path}"
        prs_json="${workspace_path}/pull-requests.json"

        if [ -n "$pr_ids_param" ]; then
          echo "[]" > "${prs_json}"
          for id in $(echo "$pr_ids_param" | tr ',' ' '); do
            response=$(curl -sS -w "\n%{http_code}" \
              "https://api.github.com/repos/${repo}/pulls/${id}")
            http_code=$(echo "$response" | tail -1)
            body=$(echo "$response" | sed '$d')
            if [ "$http_code" = "200" ]; then
              echo "$body" | jq '{number: .number, title: .title, url: .html_url}' > /tmp/pr.json
              jq -s '.[0] + [.[1]]' "${prs_json}" /tmp/pr.json > /tmp/merged.json
              mv /tmp/merged.json "${prs_json}"
            else
              echo "Warning: PR #${id} not found (HTTP ${http_code})" >&2
            fi
          done
        else
          curl -sS \
            "https://api.github.com/repos/${repo}/pulls?state=open&per_page=100" \
            | jq --arg since "${updated_since}" \
              '[.[] | select(.updated_at > $since) | {number: .number, title: .title, url: .html_url}]' \
            > "${prs_json}"
        fi

        # Generate workflow plan
        if [ -n "$gh_token" ]; then
          gh_token_display="$(printf '%*s' $((${#gh_token} - 3)) '' | tr ' ' '*')${gh_token: -3}"
        else
          gh_token_display="not provided"
        fi
        pr_count=$(jq 'length' "${prs_json}")

        cat > /tmp/workflow-plan.md <<EOF
        # PR Review Workflow Plan

        ## Configuration
        - **Repository:** ${repo}
        - **Agent:** ${agent_name}
        - **Updated Since:** ${updated_since}
        - **GitHub Token:** ${gh_token_display}
        - **Comment on PR:** ${comment_on_pr}

        ## Pull Requests to Review (${pr_count})

        | # | Title |
        |---|-------|
        EOF

        jq -r '.[] | "| [#\(.number)](\(.url)) | \(.title) |"' "${prs_json}" >> /tmp/workflow-plan.md

        cat >> /tmp/workflow-plan.md <<EOF

        ## Approval Required

        To approve: \`argo resume ${workflow_id}\`
        To reject: \`argo terminate ${workflow_id}\`
        EOF

        echo "Found ${pr_count} PRs to review"
        cat /tmp/workflow-plan.md
        jq '[.[].number]' "${prs_json}" > /tmp/pr-ids.json
    outputs:
      parameters:
      - name: pr-ids
        valueFrom:
          path: /tmp/pr-ids.json
      artifacts:
      - name: workflow-plan
        path: /tmp/workflow-plan.md
        archive:
          none: {}
      - name: pull-requests
        path: /workspace/{{workflow.name}}/pull-requests.json
        archive:
          none: {}

  - name: request-approval
    metadata:
      annotations:
        workflows.argoproj.io/description: |
          Review and approve the workflow plan before proceeding.

          The workflow plan includes:
          - Repository and configuration details
          - Validated resources
          - Planned actions

          Review the 'workflow-plan' artifact to see the complete plan.

          To approve and continue: argo resume {{workflow.name}}
          To reject and terminate: argo terminate {{workflow.name}}
    inputs:
      artifacts:
      - name: workflow-plan
    suspend: {}

  - name: review-pr
    metadata:
      annotations:
        workflows.argoproj.io/description: "Review a PR using an agent"
    retryStrategy:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
    inputs:
      parameters:
      - name: pr-id
    script:
      image: alpine/k8s:1.28.13
      command: [sh]
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail

        # Generate unique names and paths for this PR review.
        pr_id="{{inputs.parameters.pr-id}}"
        workflow_id="{{workflow.name}}"
        query_name="${workflow_id}-review-pr-${pr_id}"
        workspace_path="/workspace/${workflow_id}/${pr_id}"

        # Create Query to review PR, with instructions to use the workspace.
        kubectl create -f - <<EOF >&2
        apiVersion: ark.mckinsey.com/v1alpha1
        kind: Query
        metadata:
          name: ${query_name}
          labels:
            workflow: "{{workflow.name}}"
          annotations:
            ark.mckinsey.com/workflow-name: "{{workflow.name}}"
        spec:
          input: |
            Review pull request #${pr_id} in repository {{workflow.parameters.github-repo}}.

            Analyze the pull request and provide a review in Markdown format.

            Your review should include:
            1. PR summary and purpose
            2. Key changes
            3. Potential issues or concerns
            4. Recommendations for reviewers

          targets:
          - type: agent
            name: {{workflow.parameters.pr-review-agent}}
          sessionId: {{workflow.name}}
          timeout: 10m
          ttl: 24h
        EOF

        # Wait for query completion.
        kubectl wait --for=condition=Completed \
          --timeout=10m query/${query_name}

        # Argo's retryStrategy handles transient failures (e.g., rate limits).
        # When ARK Query 'retryCount' is enabled, retries can move to the Query level.
        # Check query status.
        phase=$(kubectl get query "${query_name}" -o jsonpath='{.status.phase}')
        if [ "${phase}" = "error" ]; then
          error_msg=$(kubectl get query "${query_name}" -o jsonpath='{.status.responses[0].raw}')
          echo "Query failed: ${error_msg}" >&2
          echo "ERROR: ${error_msg}" > /tmp/review-summary.txt
          exit 1
        fi

        # Get review content from query response.
        review_content=$(kubectl get query "${query_name}" -o jsonpath='{.status.responses[0].content}')

        # Create workspace directory and write review.
        mkdir -p "${workspace_path}"
        echo "${review_content}" > "${workspace_path}/review.md"

        # Verify file was written.
        [ -f "${workspace_path}/review.md" ] || { echo "Failed to write review file" >&2; exit 1; }

        # Output the review for workflow artifacts.
        cat "${workspace_path}/review.md" | tee /tmp/review-summary.txt
    outputs:
      parameters:
      - name: review-summary
        valueFrom:
          path: /tmp/review-summary.txt
      artifacts:
      - name: review
        path: /tmp/review-summary.txt
        archive:
          none: {}

  - name: comment-on-pr
    metadata:
      annotations:
        workflows.argoproj.io/description: "Post review comment to PR"
    inputs:
      parameters:
      - name: pr-id
    script:
      image: badouralix/curl-jq:latest
      command: [sh]
      env:
      - name: GH_TOKEN
        value: "{{workflow.parameters.gh-token}}"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail

        pr_id="{{inputs.parameters.pr-id}}"
        repo="{{workflow.parameters.github-repo}}"
        workflow_id="{{workflow.name}}"
        agent_name="{{workflow.parameters.pr-review-agent}}"
        review_file="/workspace/${workflow_id}/${pr_id}/review.md"
        marker="<!-- ark-pr-review -->"

        # Read review content from workspace.
        if [ ! -f "${review_file}" ]; then
          echo "Review file not found: ${review_file}" >&2
          exit 1
        fi
        review_content=$(cat "${review_file}")

        # Build comment body with marker and collapsible details.
        comment_body="${marker}
        ## AI Review by Agent ${agent_name}

        <details>
        <summary>Click to expand review</summary>

        ${review_content}

        </details>

        ---
        *Generated by [PR Review Workflow](https://github.com/dwmkerr/ark-demo) (${workflow_id})*"

        # Check for existing comment with marker.
        existing_comment_id=$(curl -sS \
          -H "Authorization: token ${GH_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${repo}/issues/${pr_id}/comments" \
          | jq -r ".[] | select(.body | contains(\"${marker}\")) | .id" | head -1)

        if [ -n "${existing_comment_id}" ]; then
          # Update existing comment.
          echo "Updating existing comment ${existing_comment_id}..." >&2
          comment_response=$(curl -sS -X PATCH \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${repo}/issues/comments/${existing_comment_id}" \
            -d "$(jq -n --arg body "${comment_body}" '{body: $body}')")
        else
          # Create new comment.
          echo "Creating new comment..." >&2
          comment_response=$(curl -sS -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${repo}/issues/${pr_id}/comments" \
            -d "$(jq -n --arg body "${comment_body}" '{body: $body}')")
        fi

        # Save comment URL to workspace for summary.
        comment_url=$(echo "${comment_response}" | jq -r '.html_url // empty')
        if [ -n "${comment_url}" ]; then
          echo "${comment_url}" > "/workspace/${workflow_id}/${pr_id}/comment-url.txt"
          echo "Comment URL: ${comment_url}" >&2
        fi

        # Try to add label, show warning if it fails.
        label_response=$(curl -sS -w "\n%{http_code}" -X POST \
          -H "Authorization: token ${GH_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${repo}/issues/${pr_id}/labels" \
          -d '{"labels":["ai-review"]}')

        http_code=$(echo "${label_response}" | tail -1)
        if [ "${http_code}" -ge 400 ]; then
          echo "Warning: Failed to add 'ai-review' label (HTTP ${http_code})" >&2
          echo "Create the label in the repository or check token permissions" >&2
        else
          echo "Added 'ai-review' label to PR #${pr_id}" >&2
        fi

        echo "Comment posted to PR #${pr_id}"

  - name: summarize-reviews
    metadata:
      annotations:
        workflows.argoproj.io/description: "Summarize all PR reviews from workspace"
    script:
      image: badouralix/curl-jq:latest
      command: [sh]
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail

        workflow_id="{{workflow.name}}"
        repo="{{workflow.parameters.github-repo}}"
        workspace_path="/workspace/${workflow_id}"
        summary_html="/tmp/summary.html"

        [ -d "${workspace_path}" ] || { echo "Workspace directory not found: ${workspace_path}"; exit 1; }

        # Build HTML summary.
        {
          echo "<h1>PR Review Summary</h1>"
          echo "<p>Workflow: ${workflow_id}<br>"
          echo "Repository: <a href=\"https://github.com/${repo}\">${repo}</a></p>"
          echo "<h2>Reviewed Pull Requests</h2>"
          echo "<table border=\"1\" cellpadding=\"8\" cellspacing=\"0\">"
          echo "<tr><th>PR</th><th>Review Comment</th></tr>"
        } > "${summary_html}"

        # Add row for each PR directory.
        for pr_dir in "${workspace_path}"/*/; do
          [ -d "${pr_dir}" ] || continue
          pr_id=$(basename "${pr_dir}")

          # Skip non-numeric directories.
          case "${pr_id}" in *[!0-9]*) continue ;; esac

          pr_url="https://github.com/${repo}/pull/${pr_id}"

          # Link to comment if it exists.
          if [ -f "${pr_dir}/comment-url.txt" ]; then
            comment_url=$(cat "${pr_dir}/comment-url.txt")
            review_cell="<a href=\"${comment_url}\">View</a>"
          else
            review_cell="-"
          fi

          echo "<tr><td><a href=\"${pr_url}\">PR #${pr_id}</a></td><td>${review_cell}</td></tr>" >> "${summary_html}"
        done

        echo "</table>" >> "${summary_html}"
        cat "${summary_html}"
    outputs:
      artifacts:
      - name: summary
        path: /tmp/summary.html
        archive:
          none: {}
---
# PR Review Agent with GitHub and shell MCP tools.
# This agent can interact with GitHub APIs and execute shell commands to analyze PRs.
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: pr-review-agent
spec:
  modelRef:
    name: default

  prompt: |
    You are a PR review assistant. You help analyze GitHub pull requests by:
    1. Listing open PRs in repositories
    2. Cloning repositories and checking out specific PRs
    3. Analyzing code changes

  # Add tools needed to clone/review/etc.
  tools:
  - name: github-add-comment-to-pending-review
    type: custom
  - name: github-add-issue-comment
    type: custom
  # - name: github-assign-copilot-to-issue
  #   type: custom
  # - name: github-create-branch
  #   type: custom
  # - name: github-create-or-update-file
  #   type: custom
  # - name: github-create-pull-request
  #   type: custom
  # - name: github-create-repository
  #   type: custom
  # - name: github-delete-file
  #   type: custom
  # - name: github-fork-repository
  #   type: custom
  - name: github-get-commit
    type: custom
  - name: github-get-file-contents
    type: custom
  - name: github-get-label
    type: custom
  - name: github-get-latest-release
    type: custom
  - name: github-get-me
    type: custom
  - name: github-get-release-by-tag
    type: custom
  - name: github-get-tag
    type: custom
  - name: github-get-team-members
    type: custom
  - name: github-get-teams
    type: custom
  - name: github-issue-read
    type: custom
  # - name: github-issue-write
  #   type: custom
  - name: github-list-branches
    type: custom
  - name: github-list-commits
    type: custom
  - name: github-list-issue-types
    type: custom
  - name: github-list-issues
    type: custom
  - name: github-list-pull-requests
    type: custom
  - name: github-list-releases
    type: custom
  - name: github-list-tags
    type: custom
  # - name: github-merge-pull-request
  #   type: custom
  - name: github-pull-request-read
    type: custom
  - name: github-pull-request-review-write
    type: custom
  - name: github-push-files
    type: custom
  - name: github-request-copilot-review
    type: custom
  - name: github-search-code
    type: custom
  - name: github-search-issues
    type: custom
  - name: github-search-pull-requests
    type: custom
  - name: github-search-repositories
    type: custom
  - name: github-search-users
    type: custom
  - name: github-sub-issue-write
    type: custom
  # - name: github-update-pull-request
  #   type: custom
  # - name: github-update-pull-request-branch
  #   type: custom
