apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pr-review-workflow
  annotations:
    workflows.argoproj.io/title: "Pull Requests Review"
    workflows.argoproj.io/description: |
      Analyzes all open pull requests in a GitHub repository using an ARK agent.

      GitHub Token: If gh-token is provided, the workflow can post review comments
      and status updates to PRs. Without a token, the workflow runs in read-only mode.
spec:
  entrypoint: main
  serviceAccountName: argo-workflow

  arguments:
    parameters:
    - name: github-org
      value: "mckinsey"
      description: "GitHub organization name"

    - name: github-repo
      value: "agents-at-scale-ark"
      description: "GitHub repository name"

    - name: workspace-pvc-name
      value: "github-mcp-workspace"
      description: "Name of the PVC to use for workspace"

    - name: agent-name
      value: "pr-review-agent"
      description: "ARK agent name for PR operations"

    - name: gh-token
      value: ""
      description: "GitHub token for API access. If provided, enables PR commenting and status updates."

    - name: comment-on-pr
      value: "false"
      description: "If true, post review comments to PRs. Requires gh-token to be set."

    - name: updated-since
      value: "2000-01-01T00:00:00Z"
      description: "Only review PRs updated since this timestamp. Format: ISO8601 (e.g., 2024-01-01T00:00:00Z)."

    - name: pr-ids
      value: ""
      description: "Comma-separated PR IDs to review (e.g., 234,56,2). If empty, uses all open PRs matching filters."

  templates:
  - name: main
    dag:
      tasks:
      - name: prepare-workflow
        template: prepare-workflow

      - name: validate-setup
        template: validate-setup
        dependencies: [prepare-workflow]

      - name: list-prs
        template: list-prs
        dependencies: [validate-setup]

      - name: review-prs
        template: review-pr
        dependencies: [list-prs]
        arguments:
          parameters:
          - name: pr-id
            value: "{{item}}"
        withParam: "{{tasks.list-prs.outputs.parameters.result}}"
        continueOn:
          failed: true

      - name: summarize-reviews
        template: summarize-reviews
        dependencies: [review-prs]

  - name: prepare-workflow
    metadata:
      annotations:
        workflows.argoproj.io/description: "Validate workflow parameters"
    script:
      image: alpine/k8s:1.28.13
      command: [sh]
      source: |
        set -e -o pipefail

        # Check that gh-token is provided if PR commenting is enabled.
        comment_on_pr="{{workflow.parameters.comment-on-pr}}"
        gh_token="{{workflow.parameters.gh-token}}"

        if [ "${comment_on_pr}" = "true" ] && [ -z "${gh_token}" ]; then
          echo "Error: comment-on-pr is enabled but gh-token is not set" >&2
          echo "Please provide a GitHub token to enable PR commenting" >&2
          exit 1
        fi

        echo "Workflow parameters validated successfully"

  - name: validate-setup
    metadata:
      annotations:
        workflows.argoproj.io/description: "Validate prerequisites"
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      source: |
        set -e -o pipefail

        # Verify the workspace PVC exists.
        pvc_name="{{workflow.parameters.workspace-pvc-name}}"
        echo "checking workflow pvc '${pvc_name}'..."
        kubectl get pvc "${pvc_name}"

        # Verify required MCP servers are installed.
        mcp_servers="github shell-mcp"
        for mcp_server in ${mcp_servers}; do
          echo "checking mcp server '${mcp_server}'..."
          kubectl get mcpserver "${mcp_server}"
        done

        # Verify the PR review agent exists.
        agent_name="{{workflow.parameters.agent-name}}"
        echo "checking agent '${agent_name}'..."
        kubectl get agent "${agent_name}"

  - name: list-prs
    metadata:
      annotations:
        workflows.argoproj.io/description: "List open PRs using GitHub CLI or explicit PR IDs"
    script:
      image: alpine/k8s:1.28.13
      command: [sh]
      env:
      - name: GH_TOKEN
        value: "{{workflow.parameters.gh-token}}"
      source: |
        set -e -o pipefail

        pr_ids="{{workflow.parameters.pr-ids}}"

        if [ -n "$pr_ids" ]; then
          # Use explicitly provided PR IDs, convert to JSON array.
          echo "$pr_ids" | tr ',' '\n' | jq -R . | jq -s 'map(tonumber)' > /tmp/pr-list.json
          echo "Using $(jq 'length' /tmp/pr-list.json) explicitly specified PRs"
        else
          # Query GitHub for all open PRs matching filters.
          apk add --no-cache github-cli

          gh pr list \
            --repo {{workflow.parameters.github-org}}/{{workflow.parameters.github-repo}} \
            --state open \
            --search "updated:>{{workflow.parameters.updated-since}}" \
            --json number \
            --jq '[.[].number]' > /tmp/pr-list.json

          echo "Found $(jq 'length' /tmp/pr-list.json) open PRs"
        fi
    outputs:
      parameters:
      - name: result
        valueFrom:
          path: /tmp/pr-list.json
      artifacts:
      - name: pr-list
        path: /tmp/pr-list.json
        archive:
          none: {}  # Store uncompressed for easy viewing in Argo UI

  - name: review-pr
    metadata:
      annotations:
        workflows.argoproj.io/description: "Review a PR using agent with workspace"
    inputs:
      parameters:
      - name: pr-id
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail

        # Generate unique names and paths for this PR review.
        pr_id="{{inputs.parameters.pr-id}}"
        workflow_id="{{workflow.name}}"
        query_name="${workflow_id}-review-pr-${pr_id}"
        workspace_path="/workspace/${workflow_id}/${pr_id}"

        # Create Query to review PR, with instructions to use the workspace.
        kubectl create -f - <<EOF >&2
        apiVersion: ark.mckinsey.com/v1alpha1
        kind: Query
        metadata:
          name: ${query_name}
          labels:
            workflow: "{{workflow.name}}"
          annotations:
            ark.mckinsey.com/workflow-name: "{{workflow.name}}"
        spec:
          input: |
            Review pull request #${pr_id} in repository {{workflow.parameters.github-org}}/{{workflow.parameters.github-repo}}.

            IMPORTANT: Use the following workflow:
            1. First, create the workspace directory: use execute-shell-command with 'mkdir' and args ['-p', '${workspace_path}']
            2. Change to that directory: use execute-shell-command with 'cd' and args ['${workspace_path}']
            3. Analyze the pull request using GitHub tools
            4. Write your review to ${workspace_path}/review.md using execute-shell-command with 'bash' and args ['-c', 'cat > ${workspace_path}/review.md << EOF
            <your review content here>
            EOF']

            Your review should include:
            1. PR summary and purpose
            2. Key changes
            3. Potential issues or concerns
            4. Recommendations for reviewers

            Format: Markdown
          targets:
          - type: agent
            name: {{workflow.parameters.agent-name}}
          timeout: 10m
          ttl: 24h
        EOF

        # Wait for query completion (success or failure).
        kubectl wait --for=condition=Completed \
          --timeout=10m query/${query_name}

        # Exit if the query failed.
        phase=$(kubectl get query "${query_name}" -o jsonpath='{.status.phase}')
        if [ "${phase}" = "error" ]; then
          echo "Query failed with error" >&2
          exit 1
        fi

        # Verify the agent wrote the review to the workspace.
        [ -d "${workspace_path}" ] || { echo "Workspace directory not found: ${workspace_path}" >&2; exit 1; }
        [ -f "${workspace_path}/review.md" ] || { echo "Review file not found: ${workspace_path}/review.md" >&2; exit 1; }

        # Output the review for workflow artifacts.
        cat "${workspace_path}/review.md" | tee /tmp/review-summary.txt
    volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: "{{workflow.parameters.workspace-pvc-name}}"
    outputs:
      parameters:
      - name: review-summary
        valueFrom:
          path: /tmp/review-summary.txt
      artifacts:
      - name: review
        path: /tmp/review-summary.txt
        archive:
          none: {}

  - name: summarize-reviews
    metadata:
      annotations:
        workflows.argoproj.io/description: "Summarize all PR reviews from workspace"
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      source: |
        set -e -o pipefail

        # Find all review files in the workspace.
        workflow_id="{{workflow.name}}"
        workspace_path="/workspace/${workflow_id}"

        echo "Summarizing reviews in ${workspace_path}..."

        [ -d "${workspace_path}" ] || { echo "Workspace directory not found: ${workspace_path}"; exit 1; }

        echo "PR directories:"
        find "${workspace_path}" -maxdepth 1 -type d

        echo ""
        echo "Review files:"
        find "${workspace_path}" -name "review.md" -type f | tee /tmp/summary.txt
    volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: "{{workflow.parameters.workspace-pvc-name}}"
    outputs:
      artifacts:
      - name: summary
        path: /tmp/summary.txt
        archive:
          none: {}
---
# Workspace PVC for sharing data between workflow steps.
# The agent writes PR reviews to this shared workspace, and the summarize step reads them.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-mcp-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
# PR Review Agent with GitHub and shell MCP tools.
# This agent can interact with GitHub APIs and execute shell commands to analyze PRs.
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: pr-review-agent
spec:
  modelRef:
    name: default

  prompt: |
    You are a PR review assistant. You help analyze GitHub pull requests by:
    1. Listing open PRs in repositories
    2. Cloning repositories and checking out specific PRs
    3. Analyzing code changes

  tools:
  - name: github-add-comment-to-pending-review
    type: custom
  - name: github-add-issue-comment
    type: custom
  - name: github-add-project-item
    type: custom
  - name: github-add-sub-issue
    type: custom
  - name: github-assign-copilot-to-issue
    type: custom
  - name: github-cancel-workflow-run
    type: custom
  - name: github-create-and-submit-pull-request-review
    type: custom
  - name: github-create-branch
    type: custom
  - name: github-create-gist
    type: custom
  - name: github-create-issue
    type: custom
  - name: github-create-or-update-file
    type: custom
  - name: github-create-pending-pull-request-review
    type: custom
  - name: github-create-pull-request
    type: custom
  - name: github-create-pull-request-with-copilot
    type: custom
  - name: github-create-repository
    type: custom
  - name: github-delete-file
    type: custom
  - name: github-delete-pending-pull-request-review
    type: custom
  - name: github-delete-project-item
    type: custom
  - name: github-delete-workflow-run-logs
    type: custom
  - name: github-dismiss-notification
    type: custom
  - name: github-download-workflow-run-artifact
    type: custom
  - name: github-fork-repository
    type: custom
  - name: github-get-code-scanning-alert
    type: custom
  - name: github-get-commit
    type: custom
  - name: github-get-copilot-space
    type: custom
  - name: github-get-dependabot-alert
    type: custom
  - name: github-get-discussion
    type: custom
  - name: github-get-discussion-comments
    type: custom
  - name: github-get-file-contents
    type: custom
  - name: github-get-global-security-advisory
    type: custom
  - name: github-get-issue
    type: custom
  - name: github-get-issue-comments
    type: custom
  - name: github-get-job-logs
    type: custom
  - name: github-get-latest-release
    type: custom
  - name: github-get-me
    type: custom
  - name: github-get-notification-details
    type: custom
  - name: github-get-project
    type: custom
  - name: github-get-project-field
    type: custom
  - name: github-get-project-item
    type: custom
  - name: github-get-pull-request
    type: custom
  - name: github-get-pull-request-diff
    type: custom
  - name: github-get-pull-request-files
    type: custom
  - name: github-get-pull-request-review-comments
    type: custom
  - name: github-get-pull-request-reviews
    type: custom
  - name: github-get-pull-request-status
    type: custom
  - name: github-get-release-by-tag
    type: custom
  - name: github-get-secret-scanning-alert
    type: custom
  - name: github-get-tag
    type: custom
  - name: github-get-team-members
    type: custom
  - name: github-get-teams
    type: custom
  - name: github-get-workflow-run
    type: custom
  - name: github-get-workflow-run-logs
    type: custom
  - name: github-get-workflow-run-usage
    type: custom
  - name: github-list-branches
    type: custom
  - name: github-list-code-scanning-alerts
    type: custom
  - name: github-list-commits
    type: custom
  - name: github-list-copilot-spaces
    type: custom
  - name: github-list-dependabot-alerts
    type: custom
  - name: github-list-discussion-categories
    type: custom
  - name: github-list-discussions
    type: custom
  - name: github-list-gists
    type: custom
  - name: github-list-global-security-advisories
    type: custom
  - name: github-list-issue-types
    type: custom
  - name: github-list-issues
    type: custom
  - name: github-list-notifications
    type: custom
  - name: github-list-org-repository-security-advisories
    type: custom
  - name: github-list-project-fields
    type: custom
  - name: github-list-project-items
    type: custom
  - name: github-list-projects
    type: custom
  - name: github-list-pull-requests
    type: custom
  - name: github-list-releases
    type: custom
  - name: github-list-repository-security-advisories
    type: custom
  - name: github-list-secret-scanning-alerts
    type: custom
  - name: github-list-starred-repositories
    type: custom
  - name: github-list-sub-issues
    type: custom
  - name: github-list-tags
    type: custom
  - name: github-list-workflow-jobs
    type: custom
  - name: github-list-workflow-run-artifacts
    type: custom
  - name: github-list-workflow-runs
    type: custom
  - name: github-list-workflows
    type: custom
  - name: github-manage-notification-subscription
    type: custom
  - name: github-manage-repository-notification-subscription
    type: custom
  - name: github-mark-all-notifications-read
    type: custom
  - name: github-merge-pull-request
    type: custom
  - name: github-push-files
    type: custom
  - name: github-remove-sub-issue
    type: custom
  - name: github-reprioritize-sub-issue
    type: custom
  - name: github-request-copilot-review
    type: custom
  - name: github-rerun-failed-jobs
    type: custom
  - name: github-rerun-workflow-run
    type: custom
  - name: github-run-workflow
    type: custom
  - name: github-search-code
    type: custom
  - name: github-search-issues
    type: custom
  - name: github-search-orgs
    type: custom
  - name: github-search-pull-requests
    type: custom
  - name: github-search-repositories
    type: custom
  - name: github-search-users
    type: custom
  - name: github-star-repository
    type: custom
  - name: github-submit-pending-pull-request-review
    type: custom
  - name: github-summarize-job-log-failures
    type: custom
  - name: github-summarize-run-log-failures
    type: custom
  - name: github-unstar-repository
    type: custom
  - name: github-update-gist
    type: custom
  - name: github-update-issue
    type: custom
  - name: github-update-pull-request
    type: custom
  - name: github-update-pull-request-branch
    type: custom
  - name: shell-mcp-execute-shell-command
    type: custom
