# PR Review Agent with GitHub and shell MCP tools.
# This agent can interact with GitHub APIs and execute shell commands to analyze PRs.
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: pr-review-agent
spec:
  modelRef:
    name: default

  prompt: |
    You are a PR review assistant. You help analyze GitHub pull requests by:
    1. Listing open PRs in repositories
    2. Cloning repositories and checking out specific PRs
    3. Analyzing code changes

  tools:
  - name: github-add-comment-to-pending-review
    type: custom
  - name: github-add-issue-comment
    type: custom
  - name: github-assign-copilot-to-issue
    type: custom
  - name: github-create-branch
    type: custom
  - name: github-create-or-update-file
    type: custom
  - name: github-create-pull-request
    type: custom
  - name: github-create-repository
    type: custom
  - name: github-delete-file
    type: custom
  - name: github-fork-repository
    type: custom
  - name: github-get-commit
    type: custom
  - name: github-get-file-contents
    type: custom
  - name: github-get-label
    type: custom
  - name: github-get-latest-release
    type: custom
  - name: github-get-me
    type: custom
  - name: github-get-release-by-tag
    type: custom
  - name: github-get-tag
    type: custom
  - name: github-get-team-members
    type: custom
  - name: github-get-teams
    type: custom
  - name: github-issue-read
    type: custom
  - name: github-issue-write
    type: custom
  - name: github-list-branches
    type: custom
  - name: github-list-commits
    type: custom
  - name: github-list-issue-types
    type: custom
  - name: github-list-issues
    type: custom
  - name: github-list-pull-requests
    type: custom
  - name: github-list-releases
    type: custom
  - name: github-list-tags
    type: custom
  - name: github-merge-pull-request
    type: custom
  - name: github-pull-request-read
    type: custom
  - name: github-pull-request-review-write
    type: custom
  - name: github-push-files
    type: custom
  - name: github-request-copilot-review
    type: custom
  - name: github-search-code
    type: custom
  - name: github-search-issues
    type: custom
  - name: github-search-pull-requests
    type: custom
  - name: github-search-repositories
    type: custom
  - name: github-search-users
    type: custom
  - name: github-sub-issue-write
    type: custom
  - name: github-update-pull-request
    type: custom
  - name: github-update-pull-request-branch
    type: custom
