{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    ark.mckinsey.com/dashboard-icon: "/icons/github.png"
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}
{{- end }}
