{{- if .Values.models.anthropic.enabled }}
{{- if not .Values.models.anthropic.apiKey }}
{{- fail "Anthropic models are enabled but apiKey is not set" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-api-key
  labels:
    {{- include "dwmkerr-starter-kit.labels" . | nindent 4 }}
  annotations:
    ark.mckinsey.com/dashboard-icon: "/icons/claude.png"
type: Opaque
data:
  apiKey: {{ .Values.models.anthropic.apiKey | b64enc | quote }}
{{- end }}

{{- if .Values.models.gemini.enabled }}
{{- if not .Values.models.gemini.apiKey }}
{{- fail "Gemini models are enabled but apiKey is not set" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-model-token
  labels:
    {{- include "dwmkerr-starter-kit.labels" . | nindent 4 }}
  annotations:
    ark.mckinsey.com/dashboard-icon: "/icons/gemini.png"
type: Opaque
data:
  apiKey: {{ .Values.models.gemini.apiKey | b64enc | quote }}
{{- end }}

{{- if .Values.models.azureOpenAI.enabled }}
{{- if not .Values.models.azureOpenAI.apiKey }}
{{- fail "Azure OpenAI models are enabled but apiKey is not set" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dwmkerr-azure-openai-secret
  labels:
    {{- include "dwmkerr-starter-kit.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.models.azureOpenAI.apiKey | b64enc | quote }}
{{- end }}

{{- if .Values.models.openai.enabled }}
{{- if not .Values.models.openai.apiKey }}
{{- fail "OpenAI models are enabled but apiKey is not set" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  labels:
    {{- include "dwmkerr-starter-kit.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.models.openai.apiKey | b64enc | quote }}
{{- end }}