{{- if .Values.agents }}
{{- range .Values.agents }}
{{- if or (not (hasKey . "enabled")) .enabled }}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: {{ .name }}
  labels:
    {{- include "dwmkerr-starter-kit.labels" $ | nindent 4 }}
  annotations:
    {{- if .dashboardIcon }}
    ark.mckinsey.com/dashboard-icon: {{ .dashboardIcon | quote }}
    {{- end }}
spec:
  {{- if eq .model "default" }}
  # Uses default model configured in the system
  {{- else }}
  modelRef:
    name: {{ .model }}
  {{- end }}
  prompt: |
{{ .description | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}