{{- if .Values.agents }}
{{- range .Values.agents }}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: {{ .name }}
  labels:
    {{- include "dwmkerr-starter-kit.labels" $ | nindent 4 }}
  annotations:
    {{- if or (contains "claude" .model) (contains "anthropic" .model) }}
    ark.mckinsey.com/dashboard-icon: "/icons/claude.png"
    {{- else if or (contains "gemini" .model) (contains "google" .model) }}
    ark.mckinsey.com/dashboard-icon: "/icons/gemini.png"
    {{- else if eq .model "default" }}
    ark.mckinsey.com/dashboard-icon: "/icons/azure.png"
    {{- end }}
spec:
  {{- if eq .model "default" }}
  # Uses default model configured in the system
  {{- else }}
  modelRef:
    name: {{ .model }}
  {{- end }}
  prompt: |
{{ .description | nindent 4 }}
{{- end }}
{{- end }}