{{- if .Values.teams }}
{{- range .Values.teams }}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Team
metadata:
  name: {{ .name }}
  labels:
    {{- include "dwmkerr-starter-kit.labels" $ | nindent 4 }}
spec:
  members:
  {{- range .members }}
    - name: {{ . }}
      type: agent
  {{- end }}
  strategy: {{ .strategy | default "simple" | quote }}
{{- end }}
{{- end }}