name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  mcp-servers:
    name: Build MCP Servers
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - server: shell-mcp
          - server: github-mcp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build, lint and test
        run: |
          cd mcp-servers/${{ matrix.server }}
          make init
          make lint
          make test
          make build

      - name: Validate Chart
        run: |
          cd mcp-servers/${{ matrix.server }}
          helm lint ./chart
          helm template test ./chart

  release:
    needs: [mcp-servers]
    runs-on: ubuntu-24.04
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Create Release
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          manifest-file: .github/release-please-manifest.json
          config-file: .github/release-please-config.json

  release-helm:
    name: Release Helm Chart
    needs: [release]
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${{ needs.release.outputs.tag }}
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update Helm dependencies
        run: helm dependency update ./chart

      - name: Package and push Helm chart
        run: |
          helm package ./chart
          helm push ark-demo-${{ steps.version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

  release-mcp-servers:
    name: Release MCP Server
    needs: [release]
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - server: shell-mcp
            dockerfile: mcp-servers/shell-mcp/server/Dockerfile
          - server: github-mcp
            dockerfile: ""
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: matrix.dockerfile != ''
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${{ needs.release.outputs.tag }}
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        if: matrix.dockerfile != ''
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.server }}:${{ steps.version.outputs.version }} \
            --push \
            --file ${{ matrix.dockerfile }} \
            $(dirname ${{ matrix.dockerfile }})

      - name: Package and push Helm chart
        run: |
          cd mcp-servers/${{ matrix.server }}
          helm package ./chart --version ${{ steps.version.outputs.version }} --app-version ${{ steps.version.outputs.version }}
          helm push ${{ matrix.server }}-${{ steps.version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
